import './globals.css'
import type { Metadata } from 'next'
import LeftSideBar from './components/LeftSideBar'
import RightSideBar from './components/RightSideBar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='w-full h-full flex justify-center items-center relative bg-black text-white'>
          <div className='xl:max-w-[70vw] w-full h-full flex relative'>
            <LeftSideBar />
            {children}
            <RightSideBar />
          </div>
        </div>
      </body>
    </html>
  )
}
